name: on-merge

on:
  push:
    branches: [develop]

jobs:
  build-and-deploy:
    name: Build & Deploy Frontend (Mock)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to test environment (Mock)
        run: |
          echo "Simulating deployment to https://test.dev.com"
          echo "Deploying..."
          sleep 10

  run-selenium-tests:
    name: Run Selenium Tests in ${{ matrix.browser }}
    runs-on: ubuntu-latest
    needs: build-and-deploy

    strategy:
      matrix:
        browser: [chrome, firefox, edge]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Install browsers
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            google-chrome-stable \
            firefox \
            microsoft-edge-stable 

      - name: Run Selenium tests with ${{ matrix.browser }}
        env:
          BASE_URL: "${{ secrets.BASE_URL }}"
        run: |
          source venv/bin/activate
          pytest tests --browser=${{ matrix.browser }} --html=report-${{ matrix.browser }}.html

      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: selenium-report-${{ matrix.browser }}
          path: report-${{ matrix.browser }}.html
