name: on-merge

on:
  push:
    branches: [develop]

jobs:
  build-and-deploy:
    name: Build & Deploy Frontend (Mock)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

    #   - name: Setup Node.js
    #     uses: actions/setup-node@v3
    #     with:
    #       node-version: 18.18.0

    #   - name: Install frontend dependencies
    #     run: |
    #       cd frontend
    #       npm ci

    #   - name: Build frontend
    #     run: |
    #       cd frontend
    #       npm run build

      - name: Deploy to test environment (mock)
        run: |
          echo "Simulating deployment to https://test.env.example.com"
          echo "Sleeping to simulate deploy time..."
          sleep 10

  run-selenium-tests:
    name: Run End-to-End Tests
    runs-on: ubuntu-latest
    needs: build-and-deploy

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.14.0

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Run Selenium tests against deployed frontend
        env:
          #  BASE_URL and other sensitive information should be stored as a secrets in repo settings 
          BASE_URL: "${{ secrets.BASE_URL }}" 
        run: |
          source venv/bin/activate
          pytest tests --html=report.html

      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: report
          path: report.html
